#!/bin/bash

# Regenerate sources.cmake for each JS project

set -e

root_dir=`readlink -f "$(dirname $0)"`

function echo_if_exists
{
    if [ -f "$1" ]; then
        echo "$1"
    fi
}

function update
{
    cd "$root_dir/$1"

    output=sources.cmake

    (
        echo "# Generated by js/update_sources.sh, do not edit directly"
        echo "set("
        echo "$2_SOURCES"
        echo "package.json"
        echo_if_exists .babelrc
        echo_if_exists webpack.config.js
        find src -type f | LC_ALL=C sort
        echo ")"
    ) > $output
}

update api_tests API_TESTS
update client JS_CLIENT
update webui WEBUI
