#!/bin/bash

# Regenerate sources.cmake for each project

set -e

root_dir=`readlink -f "$(dirname $0)"`

function update
{
    cd "$root_dir/$1"

    name=`echo $1 | tr a-z A-Z`

    output=sources.cmake

    (
        echo "# Generated by js/update_sources.sh, do not edit directly"
        echo "set("
        echo "${name}_SOURCES"
        echo "package.json"
        find src -type f | sort
        echo ")"
    ) > $output
}

update api_tests
update client
update webui
