image: Visual Studio 2015

install:
- scripts\get-patch.cmd
- scripts\get-foobar2000.cmd
- set PATH=%cd%\tools\patch;%PATH%

build:
  project: scripts\build.proj

configuration: Release

environment:
  EnableTests: True

test_script:
- @echo.
- @echo "=== Running server tests ==="
- @echo.
- server\build\release\src\tests\Release\core_tests.exe
- @echo.
- @echo "=== Running API tests ==="
- @echo.
- set API_TESTS_BUILD_TYPE=release
- pushd api\tests
- yarn install
- yarn test
- popd
