image: Visual Studio 2015

install:
- cmake --version
- node --version
- yarn --version
- scripts\get-patch.cmd
- scripts\get-foobar2000.cmd
- set PATH=%cd%\tools\patch;%PATH%

build:
  project: scripts\build.proj

configuration: Release

environment:
  EnableTests: True

test_script:
- server\build\release\src\tests\Release\core_tests.exe
- set API_TESTS_BUILD_TYPE=release
- pushd api\tests
- yarn install
- yarn test
- popd
