image: Visual Studio 2015

install:
- ps: Install-Product node 8
- scripts\install\patch.cmd
- scripts\install\foobar2000.cmd
- set PATH=%cd%\tools\patch;%PATH%

build_script: scripts\appveyor\build.cmd
test_script: scripts\appveyor\test.cmd
deploy_script: scripts\appveyor\upload.cmd
