set(PACKAGE_SUFFIX "-${CMAKE_PROJECT_VERSION}")

if(NOT ${PROJECT_VERSION_FINAL})
    set(PACKAGE_SUFFIX "${PACKAGE_SUFFIX}_${PROJECT_GIT_REV}")
endif()

if(${CMAKE_SIZEOF_VOID_P} STREQUAL 4)
    set(PACKAGE_SUFFIX "${PACKAGE_SUFFIX}-x86")
elseif(${CMAKE_SIZEOF_VOID_P} STREQUAL 8)
    set(PACKAGE_SUFFIX "${PACKAGE_SUFFIX}-x86_64")
endif()

set(CPACK_ARCHIVE_DEADBEEF_PLUGIN_FILE_NAME     "${DEADBEEF_PACKAGE_NAME}${PACKAGE_SUFFIX}")
set(CPACK_ARCHIVE_FOOBAR2000_PLUGIN_FILE_NAME   "${FOOBAR2000_PACKAGE_NAME}${PACKAGE_SUFFIX}")

unset(PACKAGE_SUFFIX)

set(CPACK_STRIP_FILES ON)
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)

if(OS_WINDOWS)
    set(CPACK_GENERATOR ZIP)
else()
    set(CPACK_GENERATOR TXZ)
endif()

# If there is only one component CPack ignores CPACK_ARCHIVE_COMPONENT_INSTALL
# Provide archive file name for such case

if(ENABLE_DEADBEEF)
    set(CPACK_PACKAGE_FILE_NAME ${CPACK_ARCHIVE_DEADBEEF_PLUGIN_FILE_NAME})
endif()

if(ENABLE_FOOBAR2000)
    set(CPACK_PACKAGE_FILE_NAME ${CPACK_ARCHIVE_FOOBAR2000_PLUGIN_FILE_NAME})
endif()
